version: "3.7"

services:
  wannabee-backend:
    image: ghcr.io/hochfrequenz/wanna.bee:v1.0.0-rc1
    environment:
      - StorageProvider=Directory
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    ports:
      - ${AHBICHT_FUNCTIONS_REST_PORT:-7071}:7071
